scripts/test_list: Ignore uncompiled tests
As we are using wildcards in test_config json file, script
assumes each file in the list is compiled & <file_name>.testlist
is generated. But it is not always true.

Example:
 - kms_test_config.json includes all files inside chamelium dir
 - And if we compile without chamelium tests, will endup with
   build failures.

$ meson -Dchamelium=disabled build && ninja -C build
FileNotFoundError: [Errno 2] No such file or directory: 'igt/build/tests/kms_chamelium_frames.testlist'
[1551/1555] Compiling C object 'runner/527aa9f@@runner_test@exe/runner_tests.c.o'.
ninja: build stopped: subcommand failed.
make: *** [Makefile:10: all] Error 1

So, update the scripts to just ignore if <file_name>.testlist isn't find.

$ meson -Dchamelium=disabled build && ninja -C build
[5/7] Generating kms_tests.rst with a custom command
kms_chamelium_hpd.testlist: Testlist file not found.
kms_chamelium_frames.testlist: Testlist file not found.
kms_chamelium_audio.testlist: Testlist file not found.
kms_chamelium_edid.testlist: Testlist file not found.
kms_chamelium_color.testlist: Testlist file not found.
[7/7] Generating kms_tests.html with a custom command

Cc: Mauro Carvalho Chehab <mchehab@kernel.org>
Signed-off-by: Bhanuprakash Modem <bhanuprakash.modem@intel.com>
Reviewed-by: Mauro Carvalho Chehab <mchehab@kernel.org>